In [53]:
import pandas as pd

In [54]:
# 1. Read the titanic_passengers.csv file into a DataFrame
df = pd.read_csv("assets/titanic_passengers.csv")

# View the first few rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [55]:
# Check the columns
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [56]:
# 2. Create a subset including only passengers with 3rd class tickets
third_class = df[df["Pclass"] == 3]

# View the first few rows of the subset
third_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [57]:
# 3. Using .groupby(), calculate the mean age of those who survived and those who did not survive
mean_age_by_survival = third_class.groupby("Survived")["Age"].mean()

print(mean_age_by_survival)

Survived
0    26.555556
1    20.646118
Name: Age, dtype: float64

In [58]:
# 4. Create a new feature called 'Fare in CAD'
# 1 British pound = 1.70 Canadian dollars
df["Fare in CAD"] = df["Fare"] * 1.70

# View a few rows to confirm
df[["Fare", "Fare in CAD"]].head()

      Fare  Fare in CAD
0   7.2500     12.32500
1  71.2833    121.18161
2   7.9250     13.47250
3  53.1000     90.27000
4   8.0500     13.68500

In [59]:
# 5. Create a crosstab of passenger ticket class (Pclass) and Survived
crosstab_result = pd.crosstab(df["Pclass"], df["Survived"])

print(crosstab_result)

Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

In [60]:
# This version also adds row totals, which can make it easier to read
pd.crosstab(df["Pclass"], df["Survived"], margins=True)

Survived    0    1  All
Pclass
1          80  136  216
2          97   87  184
3         372  119  491
All       549  342  891

In [61]:
# 6. Create a new feature called 'Port_name' that recodes 'Embarked'
df["Port_name"] = df["Embarked"].map({
    "S": "Southampton",
    "C": "Cherbourg",
    "Q": "Queenstown"
})

# View a few rows to confirm
df[["Embarked", "Port_name"]].head(10)

  Embarked    Port_name
0        S  Southampton
1        C    Cherbourg
2        S  Southampton
3        S  Southampton
4        S  Southampton
5        Q   Queenstown
6        S  Southampton
7        S  Southampton
8        S  Southampton
9        C    Cherbourg

In [62]:
print("Mean age of 3rd class passengers by survival status:")
print(mean_age_by_survival)
print()

print("Crosstab of Pclass and Survived:")
print(crosstab_result)
print()

print("Preview of Fare in CAD and Port_name:")
print(df[["Fare", "Fare in CAD", "Embarked", "Port_name"]].head(10))

Mean age of 3rd class passengers by survival status:
Survived
0    26.555556
1    20.646118
Name: Age, dtype: float64

Crosstab of Pclass and Survived:
Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

Preview of Fare in CAD and Port_name:
      Fare  Fare in CAD Embarked    Port_name
0   7.2500     12.32500        S  Southampton
1  71.2833    121.18161        C    Cherbourg
2   7.9250     13.47250        S  Southampton
3  53.1000     90.27000        S  Southampton
4   8.0500     13.68500        S  Southampton
5   8.4583     14.37911        Q   Queenstown
6  51.8625     88.16625        S  Southampton
7  21.0750     35.82750        S  Southampton
8  11.1333     18.92661        S  Southampton
9  30.0708     51.12036        C    Cherbourg